DROP TABLE alerta CASCADE;
DROP TABLE contrato CASCADE;
DROP TABLE equipo CASCADE;
DROP TABLE equipo_evento CASCADE;
DROP TABLE evento CASCADE;
DROP TABLE fabricante CASCADE;
DROP TABLE inventario_repuesto CASCADE;
DROP TABLE modelo CASCADE;
DROP TABLE nacionalidad CASCADE;
DROP TABLE organizacion CASCADE;
DROP TABLE parada CASCADE;
DROP TABLE patrocinador CASCADE;
DROP TABLE patrocinio CASCADE;
DROP TABLE piloto CASCADE;
DROP TABLE pista CASCADE;
DROP TABLE ranking CASCADE;
DROP TABLE ranking_por_hora CASCADE;
DROP TABLE sector CASCADE;
DROP TABLE suceso CASCADE;
DROP TABLE suceso_vehiculo CASCADE;
DROP TABLE vehiculo CASCADE;
DROP TABLE vuelta CASCADE;
DROP TYPE marcas CASCADE;
DROP TYPE persona CASCADE;
DROP TYPE tiempo CASCADE; 
DROP SEQUENCE fabricante_id_seq;
DROP SEQUENCE modelo_id_seq;
DROP SEQUENCE equipo_id_seq;
DROP SEQUENCE nacionalidad_id_seq;
DROP SEQUENCE organizacion_id_seq;
DROP SEQUENCE pista_id_seq;
DROP SEQUENCE sector_id_seq;
DROP SEQUENCE evento_id_seq;
DROP SEQUENCE piloto_id_seq;
DROP SEQUENCE vehiculo_id_seq;
DROP SEQUENCE contrato_id_seq;
DROP SEQUENCE ranking_id_seq;
DROP SEQUENCE ranking_por_hora_id_seq;
DROP SEQUENCE vuelta_id_seq;
DROP SEQUENCE patrocinador_id_seq;
DROP SEQUENCE patrocinio_id_seq;
DROP SEQUENCE suceso_id_seq;
DROP SEQUENCE suceso_vehiculo_id_seq;
DROP SEQUENCE parada_id_seq;
DROP SEQUENCE alerta_id_seq;
DROP SEQUENCE inventario_repuesto_id_seq;